// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package v1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xce3PbNhL/KigunbM7lCWn8U2qmU7rOJeMe03ji+PJTR2fByJXIloSYADQipPRd+/g",
	"QT0okBJtOZYb/ieReCwWv9/uAlzgMw55mnEGTEnc/4wzIkgKCoT5F8ZEHUf6VwQyFDRTlDPcx0cxUej4",
	"OQ4w1X8zomIcYEZSwH1MIxxgAR9yKiDCfSVyCLAMY0iJbkldZ7qUVIKyEZ5MAhwmFJh6a54v9WTeIV0J",
	"DblAiv8JDEWQ0CsQ1ygFFfOokCMGEoGYSfK/jq3eMW3XCVXd6c4YBogLlPIBTWAXBxhYnuL+OR7DAAfY",
	"PscXgWdgQ0GBRT4FvjBvNqdCyq6ogudUQGh7KHf4LgYVg9YfGoFClIU8pWykR8ZzNeL6t21EFiJ9yEFc",
	"z2SKpo3Pi1Ioo2gQB7hoz68T20mdTkyBTavmVBGVS0+nNFEgiqGjwTWStqRfCdOXyxrIgEVWASQMIVOg",
	"BY0gTCiDyK+LjIzgrQb0slzmsUF8RkaUEf0YhZwpynLiZsEnoG7y0pAE16tFAhFh/F9Te6n3U/MSKRCp",
	"RszQKimXIIyKdF8aOZASmuyhN6BywSSCNFPXiAhBrhEdIsZRSlQYg0RDnrNor0Lk4u/6kzopXpoJ1cbI",
	"mC7BMxCKgjVdAoiC6NK+WyIDQyoGpO0bGhOJXGkc4CEXqa6DI6Kgo2iqDUdJgILZl9QD4+PniA9N67aQ",
	"r7qv3hmjH3JANAKm6JCCsPbOSelrRc/HChF0EeyDnnvCB39AqHRjWovyDciMMwkederX+gdVkJofjwQM",
	"cR//oztzIF03K10zJbNeDCT0fwYf1eUcRGtgL0AJClfaLumB6JqaCrDeaP4tBBfVo1notCyDqYvmn3l0",
	"D7pQVV1FVbKmoNboWZt3QxBb23VDGPP0ck0YoXHMkTR+cdrp7bFd3U4KUur5XmrstflBEuRKaGeW5BFE",
	"aExVvKJVWeEHjnIh9Njs+2Lc03ZuauQDrHgjBQsIgV5BtGIYeRY1AkZCpEKu0proqEZrNa+sxZOXkrIQ",
	"aiRz5WKaGelAKjJIqIwbQPemptc6nXLN51RmCSk8W30b1YqRKzWztgUtafo+bak1ToVAH3KQHne7PluV",
	"sSKOrFYtSNhmkSUV0eApixbgjx1OMtoJeQQjYB34qATpKDIy/V+RhGq84D5OKftxP0jJxx+/7/VstLBi",
	"TFWTVo8xZ2yLMVSRtbr7GrgUoXgzuDg3cp9g+ZWPKKtEiQkYPV5TP0ZpLhUaACLITKaNLhGJIgFS3gIP",
	"RVwZmAYDDY8DA4/HBwcuDJdyzIVnsk/cGyubDr8JZYgolIA2qE91aCZIqJfLiLAIhYQhzpLrwiWhX4mi",
	"DCWgTJGdw87vASKdT7sBiuiIKol2ep0fdgNTWWYQUpLMt7nzc4AeBeibAH0boO8C9FOA3ue93uN/7c7b",
	"yan8eii6Jy36/88PO7+Tzqf376OfH33z7Xc/2YoXn58Gk0eb0KbW49NCj0Ehw6WAEXzMLO1mEf25m/o5",
	"ZV9Uo8ey4pVdWfc/YxJF1FqRkzk42VWCD8bCtWDwbBfoyG4yyD10OG0MDSkkkTSzNpgLI6h1UkUrWugF",
	"FGsrJWUVkw7NW1SswZYckIChABlXVX9jX1fVn6zS2jsY3FplYxhsi758431lPUmlldE8BeaJjFxFVBTY",
	"hI/Z7xVOZh7tRQ8XdeJXrrWq5D+yLwoHVPhcD8jWWjgUHvkmK4dmUX6NpDoWWBke20KN0LFiLbvuCtZJ",
	"vr4nLs/ufTpjZ0tMc44tM6O6qJMlq3Rb/7DMicUuLlbK23qBRl7Ap7yvwBm8gRGVCsQDizn9y9Df9PJz",
	"JpPtFg1AjQEY2jdh4uODg7kQcVOR3H4bEd97ROxQcVGL8ptbxTMJAkVEEaNbtf02soK5ZhyF8tYLTHQN",
	"80Fpze0gU8G8+kKme3F2G5vtlVO7RUZ8S+fVNy9nZsP09ZidCD6kCdzMx+xwtwW2e2fu5gZexivV3Tqc",
	"sp/xqlxCzXebB4Ics6wJc0HV9aleFljhnwERYL4ZDcyvF4W3+uXdW1xm9C/v3joeU4YOcxVzQT/Zr8DT",
	"LAez5ND92vZmksVKOX9D2ZCbaN58kerjw5Nj9JIoGJNrHOArENJ219vb3+vp0fMMGMko7uPv93p7PetA",
	"YyN/l+Qq7iZ8RA3nMy49i0uzF4EUN/aDZFlCw+JztZ5I8/s40oEEl0qPy1Qw3cwST879S6xZke5cysjk",
	"wrpVkOoZj65LC+g5Ebp/SPu5b/ZhuW4ht7CTWXLe2gabBxaoRj2Pe71GfXMGr4eVYy1JMfMLk6BBBRcm",
	"TC6M/KWN+f/gwGXMGPlPQXWOOP+Tgn/jgVAm0YLvQ6EpLtFOycWYiG+3NgFBy/Okt7+x2Vr84OsZ7hkj",
	"jkXavw0RZdYEhwLMfgVJpMb/QcNZvJVMx0yHpiRBpyCuQCBTwZqPPE2JuC4Ipalt7Ok51qPAF7rMlI88",
	"V7WE5LlCQ8HTJpzUbfoBvoSi+5zJbZoyZ/ENpQtbf36hzdPCbFrNVk2nI1j1fE7DSz2Xi4GWfzJdBXw3",
	"VrJ6i+neTGbVRsgqy1mz+7S1BvQLIv8ZidDUHbaUX5vyM/5Vc94u/+pIb0sgghiMi6yuKr671rYwpipv",
	"1q1lI/bvxEYsr7hX2wfvHozXNhxNP6d8xQbihy/X9xFnw4TaJeTWhXBzjPSYgGlm5Qg8zH8JCtkSZb6/",
	"BHXkXjTj+Szr2NL8Fg551Rc0Wae6NnRs5Ec0EooJL2BkvmTOwaj7mUYTC6IElC/PzTxHpMgpXoSUfWs6",
	"OY6a+w97WKQKVP7J/0oDmCe9J1+u89+4Qi94zh4c5B1aj1z++yLog3qDiaZf7qsM5y0gHmyLkV1Kdqix",
	"sy3VWqqt9C7o1Yw2S4TzL05OgUWIzOf3VrgXvULZiHPZ/MKklFJ2B3sXjXKGWhK3JL4BiQ0TX81y7Zaj",
	"RJur3plLL690ogmVJtNwIb1durR9cyCQspH5QDg7oejztfOp6c0XK+WDrWu43oUDn9vjqss5/y3JH/pq",
	"bOHA8rzDlPlAdzUA4aWdWaV17VkXe+ZehbE/jSJTiCB36GzpoEnJu+pWFsh2HNkmbki6di3X+qbNEcah",
	"eYEzTSnjDlrWcOa5LXEr0rg2Wta0rNmCHRCL54a0qY/sXBkb4Zl4bp0Ibms3mstnb9vA6u8RWK0RUTXY",
	"8J6e5vZtebsOb7AvMb3ipzX6rdHf7Lb3i+n9Az4S1Gx/F2D/p0SZTVyusep3gfkNmvXWqrdk2pA/Wded",
	"uEC+OhvH3VBW0GzdbOcp4aZR3K1ot/lNcN9FHxO3FX6nm2It1Vuqb4Dqjper2W4ususWxzxqA0dzMVOV",
	"F7VlznRrr+ChpEu3WGoQg53JhbQtk3hZG3vxMSvggiizB1IrltX1uNmIlhZOU21nClYLx3WjmNdjhk6m",
	"lmgJkhU7ovYMYxUu0Q4jKQT28Nyuf3t0HqebDzqqzlh+4U/wLVP+JkxxeK8lyywGsLfgVu6Wuntwh7x0",
	"+W2lObcVGof285fx3npRvdY1NYt4L99R0wbgD3gH1YHW4NGDfdOMbtcis3RDFqEMHZ4cI1sEBzgXiTtR",
	"LPvdbsJDksRcqv7T3tNe92rfwNV1sfQBO1cxMOW0ZFJFFk4yz66ANunwk2ApWmbQUbzDGaCQp2nOZstr",
	"VzG01zT5rxI394umhJERpPa6r+IW79mCYLnu2VzEb9NbQEhzWcJiPOfaMmqdXEz+CgAA///2L0znSV8A",
	"AA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
