// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package v1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xdbW/bthb+K5xuh7WDnDjdetEFGLYsXYdsa5u7tOvFutyAkY5tbhKpklQcr/B/v+Cb",
	"LVmkbCd24xT6llgUeXT4nOe8kKI+RAnLC0aBShEdfogKzHEOErj+LxlheZKqv1IQCSeFJIxGh9HxCEt0",
	"8iyKI6L+LbAcRXFEcQ7RYUTSKI44vC8JhzQ6lLyEOBLJCHKsepKTQrUSkhM6jKbTOEoyAlS+1r83RtLX",
	"kLoJDRhHkv0NFKWQkSvgE5SDHLHUyTECnAKfS/Lfnrm9p/tuEwpomUeH76IxXEZxlLNLkkF0HnuEHXAC",
	"NPUp5bm+sjm1EHpFJDwjHBIzwuKAb0cgR6B0goYgEaEJywkdIsYRK+WQqb9NJ8KJ9L4EPpnLlM469ynD",
	"dRjFkevPrxMzSJtOdINNq+ZMYlkKz6Akk8Ddo6PLCRKmpV8Js4tNDRRAU6MAnCRQSFCCppBkhELq10WB",
	"h/BagbQpl/5Zo7jAQ0Kx+hkljEpCS2xnwSeg6vJCAz9qV0uBhRgznv4GAmRAiFPbBnHVyNrTgLMcQY5J",
	"hjJC/w7I4URYZ6YEYJ6M/qM7ashypi8iCTxXIB6YeSsFcD1ralgFZi3YHvoNZMmpQJAXcoIw53iCyABR",
	"hnIskxEINGAlTfcC0rt/15H+CjgZkERPTkCfP2qtVRtanQrNW0w/zhfCPMTGFDt1FzX8j0eYDuF0Nvvv",
	"SxBSszlnBXBJQDcrixRLSC8cTJoP8xLGyF3dQy9KITU+MaEIS5QBFhI9RckIc5woH4EwTVGCKWI0mygC",
	"ysoU0K9YEooykLrJw6PeHzHCvX8exSglQyIFetjvffMo1jeLAhKCs2qfD7+P0YMYfRajz2P0ZYy+i9Gf",
	"Zb//+N+PojgaMJ5jqY3CPoSCvRpJyf+/d0e9P3Dvnz//TL9/8NnnX35nbjz/8DSePogWzTWOrnsMF6SX",
	"sBSGQHtwLTnuSTzU6rrCGVEKiw5nExPnhH77NM7x9bePnzyJnQwXHIZwXZh5mU/iu6bG55TBLv+CREbT",
	"uDF7omBUQHP6chACDz0+8qxMEhACuQY+WqpK5doFhPEgJ+Ggn8Nca3ghiuQI1BRKNMYC2dbV2VJq6EmS",
	"e4RzLvWCeAB58gyxge7dNPLd7rvvDSXvS0AkBSrJgAA3wYOV0teLMtMlIqgmXuV6tSjCM6lk0H8QCbn+",
	"4wGHQXQY/Wt/Ho3tWwPf11MyH0UTn/qfwrW8qPiGFn/DQXICVyogUA+i7lQ+CFZ7mh85Zzz8NLVBG/So",
	"7kXV3zy6B9UodK8kMluOadOFD9EmBDERyA2RbSKJG2Kb5RcrYguNR8y6jdmgtwd8uJ8gobzSf+DMMYpj",
	"9hSNiRwt6VUEorLjknP1bOa6e+5ZPzcNueJIsrUUzCEBcgXpksdw1L0qMDLlG+1NK6JjGkRr2NgMDYoL",
	"QWgCLZLZdiNSaOlASHyZETFaA7o35WMT1Cze+YyIIsMuqGvvI6wYsVQzK9PqgqbvkmANOTmBAtHb6tYq",
	"NYtYYzVqQdx0i4xRYQWem4dDKgo60FHQV/2+iXqWPFNo0toxZsnWPUPIWMPDt8DFJcbrwcW6kbsEy69s",
	"SGgQJSbNCGQpuQroLwFhpCfTZnw4TTkIsYnwWHeog+QnLkiuJaYt6WjeJRu3TDZchtmabFj0GKt4Yepc",
	"hx8inKbEsMhpBU4mC/XBmNseNJ5NuQyZMp7YQ0ezztCAQJYKPWuXlTCCGCflelFC11CMdUITsqQjk+64",
	"rHm1+Ei5f11/ajTnMOAgRqHRfjOXQ8NNlyn5LVzeWsNjuLyn6g2oh5XyjhPdF+ZakEgVFQH1BH/2RuQa",
	"bMKNHvSdH62K70ZoFT+YY4bkPzYXnI8N6jJeLTdyQcdNkqP1EpkWSVW4szQDMI1Wg6hV75IcftXM3Uq+",
	"erCxOLt3GW9Y/tPdWWuZ+426ThpMelsX2LSJ+hDnS+X9pB3d5j2XT3mfmAPzP/aQCAn8noXV/kz7pcqw",
	"5zKZYdElyDEARQc6En785EklCt5UsHrQBf13HvRbVJy3ovzmrKgDvRRLrHUrd58jA5arn8Mp77YZhN8O",
	"9Q360kei7vrsrk3bS6d2p7KQnZxX/7wIkEvXZnfRwXip5nz5I95pXvdGl+BfjekpZwOStSR4Zj2iZTXc",
	"rVi4Fughs6XWR3uo82HefLbNdcXtKJ9rd2uAv0Eg5ZVquzFVM5RavnPDwD7tsLohrPqYXBF/mN3ujUP6",
	"3WiBMLp0YV9ikolwFPGhKeHiTjzI0p5GxIAk6Go2MtLr9WIP/QITgTAHE0TopxCxaliC+V03RLMKShzB",
	"Nc4LE7ZalUeEVmnCAqqagEQz0/VhPvJpqXVPwqqOynQSzzTpc1i/AyeDiabAO3WduoyWlJzIyVkygtwM",
	"/ANgDloPl/qv585af377Olqc7p/fvrZxI6HoqJQjxsk/Zr5nW3N1iUuNa/qbCzyS0hoeoQOmwaV3fhxG",
	"R6cn6CcsYYwnkd6TJ8xw/b2Dvb5SISuA4oJEh9FXe/29viGQkZZ/H5dytJ/oLVa9Kn0WTEjvxmY6tJsF",
	"ZlRaCkX2/v2Se8hUO4hABWdXRAW+WCC9wQ/NNlOjh7A33IuRV5rvdJ/fvn71y48vFSGqeddKO1HIPWVC",
	"KlXWd4npR5zv1H7nLyfOm+x7toZOzw00QMgfWDpZKBrjosjshsb9v4TZ2jPfj7ik6unZjbgQTqoERP9g",
	"EK/n6nG/vzUhXCF12uComXM005IiYUxqUGaZrrR+vaZYjMKrQXBOnIAhFp7G7fcttD73PNEPOEVW7aiH",
	"Tiw5GuSyOa7Nsx1sTOULkjXlekOx5QRIUc8aDlwXChFKMEvjSq4nG4TCUrlOqAo2cIbOgF8BR/oGQ4hl",
	"nmM+mRNDxf5MUPEuUs8UnavWxrozNiQ0zDB6bRBJpnPjykMFDV/fsLa9V96p2Jad1zYibMG8V7Ojxlrr",
	"MgPyrYB7zejVL1FsXynR8p+B7B0z9jcB/6IaJlSgWl0HJbq5QA8Xyic6un7Uupt/egPmuRHfLOOP3xeC",
	"trulDTJwNIESDnqREGdiJynDGW4LUbBStjIFK6WJNdYgC9XnFh3rwuK9327uEiK7hAUbT2sSc5H0u3NF",
	"yDWYmCkL4cRSShgos2KxAkm9bOpHib0h2o5fCC8Y35mTCC1rLvMVLWvJncu4Jy7jvvHB3DjDhGBWetoY",
	"wbRAGFEYuxdXQmRge9vBEHNxXX4lAjnYCoE0F9eWk4d3udVLHMeznVMde/jZ45uPZ8DHjA4yYqpzOxdV",
	"Vsw1zA8C5ArFLl0L8ta6XL06xBiV5b6tBRGeVdOPXEPyL2u2lZBMjdCUoYUa/9MpH5mHmp3A4Mo2mLpL",
	"Yyz089NdtRs1NSvUb/Sr3JPebDlnCB7TMUV7Yzu1xUlrQKHX6usG9RNoe6qsAKzthJtvqBtfvCWT8C1W",
	"eCak+lL8BiqqtwKHH86Mo5yI+VzF9xjaFowOQB5gz1449oL5J5DItPAA9NheWHe5wZ2CsVU41t+z7moR",
	"t809FBLchDsY6Y3uFRjtfyDp1IAoA+l701P/jrB71b4OKXNVD3Ky/jKWPZAoBCr/5N8N2dw58L7uf/3x",
	"Bn/JJHrOSnrvIG/RemyPhaiDPm4nzOq2BD9x3gLi8a6QbONdmBae7UytM7Wl3gW9mJtNw+D8qeoZ0BTh",
	"6hvuAfeictSNOJfNp7QLbxx+5GS28UrZpox4l/LVjgjuBRFoa34x37HWjDTNiQ+9yiENQUecEaFfZq0d",
	"EiHs4Rf6RDmV5Klkbn7qns9fVw94WD/hWTyscQX3XTvEcHfc/eLJGZ23v+8ZXe0QzqrTFeWlGuoSuNfs",
	"dKa3b06MMWfDymTkf1OnkAgje3RT47iWBQ+teqkZ20lqurih0XX5YOebNmcwFs01m1nXZOxxZS0288y0",
	"uJXR2D46q+msZgeqKAbPa5pNe2Rn25gIT8dzq0RwO1usXjzBrgusPo3AaoWIao2i+exMRF/Z3A54g9rG",
	"7Nj6jvQ70t9s6fz57BRPnxG0lNAd2L/Q704NSAYtrL4NzG+Q1jtW74xpQ/5kVXdiA/nw/i771Q1nZqu+",
	"dDQzuFkUdyuz23wh3Xdc7tSW07daFOtMvTP1DZi6tcvl1q6/hLLvXvlvDRzNLs6AFzVt3qjeXkC0TvzX",
	"Yel+xGBvRG1HsN7w3xp7sTF1cEGEmiMTAml1O242oqXayRq7uY2rg+OqUcyrMUWnMyZqQDJQETUH2IRw",
	"iR5SnENs9mM+8pdHqzjdfNAROlfqIy/jr2op3VtgnQnfzIStIbZa8Tw4Md93C5Zx7RfeBmzhs25BP2Nu",
	"WDvnqH5m7tbZ/kpHNNcNcfF85i4zuMelXQtajUcP9nU3ql+DzIXT4TGh6Oj0BJkmURyVPLOnG4nD/f2M",
	"JTgbMSEPn/af9vevDjRc7RCNlfVSjoBK911BTNP6qUrzLwjqvf7TuBHGU+hJ1mMUUMLyvKTzvN/emJgj",
	"yv3f7dSfD8oxxUPIzVH37pOZ80ylee+bSipi9t0AF/qg0HqgafvSap2eT/8fAAD//6zhW7GKdgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
