apiVersion: v1
kind: Service
metadata:
  name: subscriber-service
  namespace: messenger
  labels:
    app: subscriber-service
spec:
  type: ClusterIP
  selector:
    app: subscriber-service
  ports:
    - name: http
      protocol: TCP
      port: 8084
      targetPort: 8084
