apiVersion: v1
kind: Service
metadata:
  name: sso-service
  namespace: messenger
  labels:
    app: sso-service
spec:
  type: ClusterIP
  selector:
    app: sso-service
  ports:
    - name: grpc
      protocol: TCP
      port: 44044
      targetPort: 44044
