apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: messenger
  labels:
    app: auth-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: msa-messenger/auth:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          startupProbe:
            httpGet:
              path: /health
              port: 8081
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 10
  strategy:
    type: RollingUpdate # Recrate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
