apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: messenger
  labels:
    app: notification-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: msa-messenger/notification:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8085
          volumeMounts:
            - name: notification-config
              mountPath: /config
              readOnly: true
          startupProbe:
            httpGet:
              path: /health
              port: 8085
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8085
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 8085
            initialDelaySeconds: 15
            periodSeconds: 10
      volumes:
        - name: notification-config
          configMap:
            name: notification-config
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
