// Package handler provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package handler

import (
	"encoding/json"
	"fmt"
	"time"
)

const (
	BearerScopes = "Bearer.Scopes"
)

// Defines values for FriendInviteStatus.
const (
	FriendInviteStatusAccepted FriendInviteStatus = "accepted"
	FriendInviteStatusDeclined FriendInviteStatus = "declined"
	FriendInviteStatusPending  FriendInviteStatus = "pending"
)

// Defines values for ClientType.
const (
	ClientTypeMobile ClientType = "mobile"
	ClientTypeWeb    ClientType = "web"
)

// Defines values for InviteDirection.
const (
	InviteDirectionIncoming InviteDirection = "incoming"
	InviteDirectionOutgoing InviteDirection = "outgoing"
)

// Defines values for InviteStatus.
const (
	InviteStatusAccepted InviteStatus = "accepted"
	InviteStatusDeclined InviteStatus = "declined"
	InviteStatusPending  InviteStatus = "pending"
)

// Defines values for PostAuthLoginParamsXClientType.
const (
	PostAuthLoginParamsXClientTypeMobile PostAuthLoginParamsXClientType = "mobile"
	PostAuthLoginParamsXClientTypeWeb    PostAuthLoginParamsXClientType = "web"
)

// Defines values for PostAuthRegisterParamsXClientType.
const (
	Mobile PostAuthRegisterParamsXClientType = "mobile"
	Web    PostAuthRegisterParamsXClientType = "web"
)

// Defines values for GetFriendInvitesParamsDirection.
const (
	GetFriendInvitesParamsDirectionIncoming GetFriendInvitesParamsDirection = "incoming"
	GetFriendInvitesParamsDirectionOutgoing GetFriendInvitesParamsDirection = "outgoing"
)

// Defines values for GetFriendInvitesParamsStatus.
const (
	Accepted GetFriendInvitesParamsStatus = "accepted"
	Declined GetFriendInvitesParamsStatus = "declined"
	Pending  GetFriendInvitesParamsStatus = "pending"
)

// ChangePasswordRequest defines model for ChangePasswordRequest.
type ChangePasswordRequest struct {
	// UpdatedPassword New password. Must contain at least 8 characters and can only include Latin letters (A-Z, a-z), digits (0-9), and special characters (@, $, !, %, *, ?, &)
	UpdatedPassword string `json:"updated_password" validate:"required,min=8,max=255,password_regexp"`
}

// ChangePasswordResponse defines model for ChangePasswordResponse.
type ChangePasswordResponse struct {
	// Message Success message
	Message string `json:"message"`
}

// Chat defines model for Chat.
type Chat struct {
	// CreatedAt When the chat was created
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// FriendId ID of the friend
	FriendId *string `json:"friend_id,omitempty"`

	// Id Unique identifier for the chat
	Id *string `json:"id,omitempty"`

	// UserId ID of the user
	UserId *string `json:"user_id,omitempty"`
}

// ChatsResponse defines model for ChatsResponse.
type ChatsResponse struct {
	Chats *[]Chat `json:"chats,omitempty"`

	// NextPageToken Token for retrieving the next page
	NextPageToken *string `json:"next_page_token,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Description Error description
	Description *string `json:"description,omitempty"`

	// Error Error title
	Error string `json:"error"`
}

// FriendInvite defines model for FriendInvite.
type FriendInvite struct {
	// CreatedAt When the invite was created
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// FromUserId ID of the user who sent the invite
	FromUserId *string `json:"from_user_id,omitempty"`

	// Id Unique identifier for the invite
	Id *string `json:"id,omitempty"`

	// Message Optional message included with the invite
	Message *string `json:"message,omitempty"`

	// Status Current status of the invite
	Status *FriendInviteStatus `json:"status,omitempty"`

	// ToUserId ID of the user who received the invite
	ToUserId *string `json:"to_user_id,omitempty"`

	// UpdatedAt When the invite was last updated
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// FriendInviteStatus Current status of the invite
type FriendInviteStatus string

// FriendResponse defines model for FriendResponse.
type FriendResponse struct {
	// FriendsSince When the friendship was established
	FriendsSince *time.Time `json:"friends_since,omitempty"`

	// Id ID of the friend
	Id *string `json:"id,omitempty"`

	// Name Display name of the friend
	Name *string `json:"name,omitempty"`
}

// FriendsResponse defines model for FriendsResponse.
type FriendsResponse struct {
	Friends *[]FriendResponse `json:"friends,omitempty"`

	// NextPageToken Token for retrieving the next page
	NextPageToken *string `json:"next_page_token,omitempty"`
}

// InviteFriendRequest defines model for InviteFriendRequest.
type InviteFriendRequest struct {
	// Message Optional message to send with friend request acceptance
	Message *string `json:"message,omitempty" validate:"min=1,max=300"`
}

// InviteFriendResponse defines model for InviteFriendResponse.
type InviteFriendResponse struct {
	// Id ID of the created friend invite
	Id *string `json:"id,omitempty"`
}

// InvitesResponse defines model for InvitesResponse.
type InvitesResponse struct {
	Invites *[]FriendInvite `json:"invites,omitempty"`

	// NextPageToken Token for retrieving the next page
	NextPageToken *string `json:"next_page_token,omitempty"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	// Email Email must be a valid email address
	Email string `json:"email" validate:"required,email,min=5,max=255"`

	// Password Password must contain at least 8 characters and can only include Latin letters (A-Z, a-z), digits (0-9), and special characters (@, $, !, %, *, ?, &)
	Password string `json:"password" validate:"required,min=8,max=255,password_regexp"`
}

// LoginResponseMobile Token response for mobile clients. Additional fields can be included in the response
type LoginResponseMobile struct {
	// AccessToken Access token
	AccessToken *string `json:"access_token,omitempty"`

	// Id User ID
	Id *string `json:"id,omitempty"`

	// RefreshToken Refresh token
	RefreshToken         *string                `json:"refresh_token,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// LoginResponseWeb Token response for web clients. Additional fields can be included in the response
type LoginResponseWeb struct {
	// AccessToken Access token
	AccessToken *string `json:"access_token,omitempty"`

	// Id User ID
	Id                   *string                `json:"id,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// LogoutResponse defines model for LogoutResponse.
type LogoutResponse struct {
	// Message Success message
	Message string `json:"message"`
}

// MessageRequest defines model for MessageRequest.
type MessageRequest struct {
	// Content Message content
	Content string `json:"content" validate:"min=1,max=1000"`
}

// MessageResponse defines model for MessageResponse.
type MessageResponse struct {
	// Content Content of the message
	Content *string `json:"content,omitempty"`

	// CreatedAt When the message was created
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// Id Unique identifier for the message
	Id *string `json:"id,omitempty"`

	// SenderId ID of the sender
	SenderId *string `json:"sender_id,omitempty"`
}

// MessagesResponse defines model for MessagesResponse.
type MessagesResponse struct {
	Chat     *Chat              `json:"chat,omitempty"`
	Messages *[]MessageResponse `json:"messages,omitempty"`

	// NextPageToken Token for retrieving the next page
	NextPageToken *string `json:"next_page_token,omitempty"`
}

// RefreshTokenRequestMobile defines model for RefreshTokenRequestMobile.
type RefreshTokenRequestMobile struct {
	RefreshToken string `json:"refresh_token" validate:"required"`
}

// RefreshTokenResponseMobile Token response for mobile clients. Additional fields can be included in the response
type RefreshTokenResponseMobile struct {
	// AccessToken Access token
	AccessToken *string `json:"access_token,omitempty"`

	// RefreshToken Refresh token
	RefreshToken         *string                `json:"refresh_token,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// RefreshTokenResponseWeb Token response for web clients. Additional fields can be included in the response
type RefreshTokenResponseWeb struct {
	// AccessToken Access token
	AccessToken          *string                `json:"access_token,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	// Email Email must be a valid email address
	Email string `json:"email" validate:"required,email,min=5,max=255"`

	// Name Name must be a string between 1 and 255 characters
	Name string `json:"name" validate:"required,min=1,max=255"`

	// Password Password must contain at least 8 characters and can only include Latin letters (A-Z, a-z), digits (0-9), and special characters (@, $, !, %, *, ?, &)
	Password string `json:"password" validate:"required,min=8,max=255,password_regexp"`
}

// RegisterResponseMobile User data and token response for mobile clients. Additional fields can be included in the response
type RegisterResponseMobile struct {
	// AccessToken Access token
	AccessToken *string `json:"access_token,omitempty"`

	// Email User email
	Email *string `json:"email,omitempty"`

	// Id User ID
	Id *string `json:"id,omitempty"`

	// Name User name
	Name *string `json:"name,omitempty"`

	// RefreshToken Refresh token
	RefreshToken         *string                `json:"refresh_token,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// RegisterResponseWeb User data and token response for web clients. Additional fields can be included in the response
type RegisterResponseWeb struct {
	// AccessToken Access token
	AccessToken *string `json:"access_token,omitempty"`

	// Email User email
	Email *string `json:"email,omitempty"`

	// Id User ID
	Id *string `json:"id,omitempty"`

	// Name User name
	Name                 *string                `json:"name,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// ResetPasswordRequest defines model for ResetPasswordRequest.
type ResetPasswordRequest struct {
	// Email Email must be a valid email address
	Email string `json:"email" validate:"required,email,min=5,max=255"`
}

// ResetPasswordResponse defines model for ResetPasswordResponse.
type ResetPasswordResponse struct {
	// Message Success message
	Message string `json:"message"`
}

// UpdateOwnProfileRequest defines model for UpdateOwnProfileRequest.
type UpdateOwnProfileRequest struct {
	// CurrentPassword Current password (optional). Password must contain at least 8 characters and can only include Latin letters (A-Z, a-z), digits (0-9), and special characters (@, $, !, %, *, ?, &)
	CurrentPassword *string `json:"current_password,omitempty" validate:"min=8,max=255,password_regexp"`

	// Email Email (optional) must be a valid email address
	Email *string `json:"email,omitempty" validate:"email,min=5,max=255"`

	// Name Name (optional) must be a string between 1 and 255 characters
	Name *string `json:"name,omitempty" validate:"min=1,max=255"`

	// UpdatedPassword Updated password (optional). Password must contain at least 8 characters and can only include Latin letters (A-Z, a-z), digits (0-9), and special characters (@, $, !, %, *, ?, &)
	UpdatedPassword *string `json:"updated_password,omitempty" validate:"min=8,max=255,password_regexp"`
}

// UserResponse defines model for UserResponse.
type UserResponse struct {
	// Email User email
	Email *string `json:"email,omitempty"`

	// Id User ID
	Id *string `json:"id,omitempty"`

	// Name User name
	Name *string `json:"name,omitempty"`
}

// ValidationErrorResponse defines model for ValidationErrorResponse.
type ValidationErrorResponse struct {
	// Details Field-specific validation errors. Keys are field names, values are error messages
	Details map[string]string `json:"details"`

	// Error Error message
	Error string `json:"error"`
}

// VerifyEmailResponse defines model for VerifyEmailResponse.
type VerifyEmailResponse struct {
	// Message Success message
	Message string `json:"message"`
}

// ChatId defines model for chatId.
type ChatId = string

// ClientType defines model for clientType.
type ClientType string

// FriendId defines model for friendId.
type FriendId = string

// InviteDirection defines model for inviteDirection.
type InviteDirection string

// InviteId defines model for inviteId.
type InviteId = string

// InviteStatus defines model for inviteStatus.
type InviteStatus string

// PageToken defines model for pageToken.
type PageToken = string

// PasswordResetToken defines model for passwordResetToken.
type PasswordResetToken = string

// SearchQuery defines model for searchQuery.
type SearchQuery = string

// VerificationToken defines model for verificationToken.
type VerificationToken = string

// PostAuthChangePasswordParams defines parameters for PostAuthChangePassword.
type PostAuthChangePasswordParams struct {
	// Token Password reset token from email link
	Token PasswordResetToken `form:"token" json:"token"`
}

// PostAuthLoginParams defines parameters for PostAuthLogin.
type PostAuthLoginParams struct {
	// XClientType Client type for token delivery method
	XClientType PostAuthLoginParamsXClientType `json:"X-Client-Type"`
}

// PostAuthLoginParamsXClientType defines parameters for PostAuthLogin.
type PostAuthLoginParamsXClientType string

// PostAuthRegisterParams defines parameters for PostAuthRegister.
type PostAuthRegisterParams struct {
	// XClientType Client type for token delivery method
	XClientType PostAuthRegisterParamsXClientType `json:"X-Client-Type"`
}

// PostAuthRegisterParamsXClientType defines parameters for PostAuthRegister.
type PostAuthRegisterParamsXClientType string

// GetAuthVerifyEmailParams defines parameters for GetAuthVerifyEmail.
type GetAuthVerifyEmailParams struct {
	// Token Email verification token sent to user's email
	Token VerificationToken `form:"token" json:"token"`
}

// GetChatsParams defines parameters for GetChats.
type GetChatsParams struct {
	// PageToken Token for pagination continuation
	PageToken *PageToken `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// GetChatsIdParams defines parameters for GetChatsId.
type GetChatsIdParams struct {
	// PageToken Token for pagination continuation
	PageToken *PageToken `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// GetFriendInvitesParams defines parameters for GetFriendInvites.
type GetFriendInvitesParams struct {
	// Direction Whether to get incoming or outgoing invites
	Direction *GetFriendInvitesParamsDirection `form:"direction,omitempty" json:"direction,omitempty"`

	// Status Filter invites by status
	Status *GetFriendInvitesParamsStatus `form:"status,omitempty" json:"status,omitempty"`

	// PageToken Token for pagination continuation
	PageToken *PageToken `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// GetFriendInvitesParamsDirection defines parameters for GetFriendInvites.
type GetFriendInvitesParamsDirection string

// GetFriendInvitesParamsStatus defines parameters for GetFriendInvites.
type GetFriendInvitesParamsStatus string

// GetFriendsParams defines parameters for GetFriends.
type GetFriendsParams struct {
	// PageToken Token for pagination continuation
	PageToken *PageToken `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// GetUsersSearchParams defines parameters for GetUsersSearch.
type GetUsersSearchParams struct {
	// Query Search term to filter users by name or email. Returns empty array if no matches found.
	Query SearchQuery `form:"query" json:"query"`
}

// PostAuthChangePasswordJSONRequestBody defines body for PostAuthChangePassword for application/json ContentType.
type PostAuthChangePasswordJSONRequestBody = ChangePasswordRequest

// PostAuthLoginJSONRequestBody defines body for PostAuthLogin for application/json ContentType.
type PostAuthLoginJSONRequestBody = LoginRequest

// PostAuthRefreshJSONRequestBody defines body for PostAuthRefresh for application/json ContentType.
type PostAuthRefreshJSONRequestBody = RefreshTokenRequestMobile

// PostAuthRegisterJSONRequestBody defines body for PostAuthRegister for application/json ContentType.
type PostAuthRegisterJSONRequestBody = RegisterRequest

// PostAuthResetPasswordJSONRequestBody defines body for PostAuthResetPassword for application/json ContentType.
type PostAuthResetPasswordJSONRequestBody = ResetPasswordRequest

// PostChatsIdJSONRequestBody defines body for PostChatsId for application/json ContentType.
type PostChatsIdJSONRequestBody = MessageRequest

// PostFriendsIdInviteJSONRequestBody defines body for PostFriendsIdInvite for application/json ContentType.
type PostFriendsIdInviteJSONRequestBody = InviteFriendRequest

// PatchUsersMeJSONRequestBody defines body for PatchUsersMe for application/json ContentType.
type PatchUsersMeJSONRequestBody = UpdateOwnProfileRequest

// Getter for additional properties for LoginResponseMobile. Returns the specified
// element and whether it was found
func (a LoginResponseMobile) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for LoginResponseMobile
func (a *LoginResponseMobile) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for LoginResponseMobile to handle AdditionalProperties
func (a *LoginResponseMobile) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["access_token"]; found {
		err = json.Unmarshal(raw, &a.AccessToken)
		if err != nil {
			return fmt.Errorf("error reading 'access_token': %w", err)
		}
		delete(object, "access_token")
	}

	if raw, found := object["id"]; found {
		err = json.Unmarshal(raw, &a.Id)
		if err != nil {
			return fmt.Errorf("error reading 'id': %w", err)
		}
		delete(object, "id")
	}

	if raw, found := object["refresh_token"]; found {
		err = json.Unmarshal(raw, &a.RefreshToken)
		if err != nil {
			return fmt.Errorf("error reading 'refresh_token': %w", err)
		}
		delete(object, "refresh_token")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for LoginResponseMobile to handle AdditionalProperties
func (a LoginResponseMobile) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.AccessToken != nil {
		object["access_token"], err = json.Marshal(a.AccessToken)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'access_token': %w", err)
		}
	}

	if a.Id != nil {
		object["id"], err = json.Marshal(a.Id)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'id': %w", err)
		}
	}

	if a.RefreshToken != nil {
		object["refresh_token"], err = json.Marshal(a.RefreshToken)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'refresh_token': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for LoginResponseWeb. Returns the specified
// element and whether it was found
func (a LoginResponseWeb) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for LoginResponseWeb
func (a *LoginResponseWeb) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for LoginResponseWeb to handle AdditionalProperties
func (a *LoginResponseWeb) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["access_token"]; found {
		err = json.Unmarshal(raw, &a.AccessToken)
		if err != nil {
			return fmt.Errorf("error reading 'access_token': %w", err)
		}
		delete(object, "access_token")
	}

	if raw, found := object["id"]; found {
		err = json.Unmarshal(raw, &a.Id)
		if err != nil {
			return fmt.Errorf("error reading 'id': %w", err)
		}
		delete(object, "id")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for LoginResponseWeb to handle AdditionalProperties
func (a LoginResponseWeb) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.AccessToken != nil {
		object["access_token"], err = json.Marshal(a.AccessToken)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'access_token': %w", err)
		}
	}

	if a.Id != nil {
		object["id"], err = json.Marshal(a.Id)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'id': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for RefreshTokenResponseMobile. Returns the specified
// element and whether it was found
func (a RefreshTokenResponseMobile) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for RefreshTokenResponseMobile
func (a *RefreshTokenResponseMobile) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for RefreshTokenResponseMobile to handle AdditionalProperties
func (a *RefreshTokenResponseMobile) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["access_token"]; found {
		err = json.Unmarshal(raw, &a.AccessToken)
		if err != nil {
			return fmt.Errorf("error reading 'access_token': %w", err)
		}
		delete(object, "access_token")
	}

	if raw, found := object["refresh_token"]; found {
		err = json.Unmarshal(raw, &a.RefreshToken)
		if err != nil {
			return fmt.Errorf("error reading 'refresh_token': %w", err)
		}
		delete(object, "refresh_token")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for RefreshTokenResponseMobile to handle AdditionalProperties
func (a RefreshTokenResponseMobile) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.AccessToken != nil {
		object["access_token"], err = json.Marshal(a.AccessToken)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'access_token': %w", err)
		}
	}

	if a.RefreshToken != nil {
		object["refresh_token"], err = json.Marshal(a.RefreshToken)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'refresh_token': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for RefreshTokenResponseWeb. Returns the specified
// element and whether it was found
func (a RefreshTokenResponseWeb) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for RefreshTokenResponseWeb
func (a *RefreshTokenResponseWeb) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for RefreshTokenResponseWeb to handle AdditionalProperties
func (a *RefreshTokenResponseWeb) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["access_token"]; found {
		err = json.Unmarshal(raw, &a.AccessToken)
		if err != nil {
			return fmt.Errorf("error reading 'access_token': %w", err)
		}
		delete(object, "access_token")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for RefreshTokenResponseWeb to handle AdditionalProperties
func (a RefreshTokenResponseWeb) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.AccessToken != nil {
		object["access_token"], err = json.Marshal(a.AccessToken)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'access_token': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for RegisterResponseMobile. Returns the specified
// element and whether it was found
func (a RegisterResponseMobile) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for RegisterResponseMobile
func (a *RegisterResponseMobile) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for RegisterResponseMobile to handle AdditionalProperties
func (a *RegisterResponseMobile) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["access_token"]; found {
		err = json.Unmarshal(raw, &a.AccessToken)
		if err != nil {
			return fmt.Errorf("error reading 'access_token': %w", err)
		}
		delete(object, "access_token")
	}

	if raw, found := object["email"]; found {
		err = json.Unmarshal(raw, &a.Email)
		if err != nil {
			return fmt.Errorf("error reading 'email': %w", err)
		}
		delete(object, "email")
	}

	if raw, found := object["id"]; found {
		err = json.Unmarshal(raw, &a.Id)
		if err != nil {
			return fmt.Errorf("error reading 'id': %w", err)
		}
		delete(object, "id")
	}

	if raw, found := object["name"]; found {
		err = json.Unmarshal(raw, &a.Name)
		if err != nil {
			return fmt.Errorf("error reading 'name': %w", err)
		}
		delete(object, "name")
	}

	if raw, found := object["refresh_token"]; found {
		err = json.Unmarshal(raw, &a.RefreshToken)
		if err != nil {
			return fmt.Errorf("error reading 'refresh_token': %w", err)
		}
		delete(object, "refresh_token")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for RegisterResponseMobile to handle AdditionalProperties
func (a RegisterResponseMobile) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.AccessToken != nil {
		object["access_token"], err = json.Marshal(a.AccessToken)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'access_token': %w", err)
		}
	}

	if a.Email != nil {
		object["email"], err = json.Marshal(a.Email)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'email': %w", err)
		}
	}

	if a.Id != nil {
		object["id"], err = json.Marshal(a.Id)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'id': %w", err)
		}
	}

	if a.Name != nil {
		object["name"], err = json.Marshal(a.Name)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'name': %w", err)
		}
	}

	if a.RefreshToken != nil {
		object["refresh_token"], err = json.Marshal(a.RefreshToken)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'refresh_token': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for RegisterResponseWeb. Returns the specified
// element and whether it was found
func (a RegisterResponseWeb) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for RegisterResponseWeb
func (a *RegisterResponseWeb) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for RegisterResponseWeb to handle AdditionalProperties
func (a *RegisterResponseWeb) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["access_token"]; found {
		err = json.Unmarshal(raw, &a.AccessToken)
		if err != nil {
			return fmt.Errorf("error reading 'access_token': %w", err)
		}
		delete(object, "access_token")
	}

	if raw, found := object["email"]; found {
		err = json.Unmarshal(raw, &a.Email)
		if err != nil {
			return fmt.Errorf("error reading 'email': %w", err)
		}
		delete(object, "email")
	}

	if raw, found := object["id"]; found {
		err = json.Unmarshal(raw, &a.Id)
		if err != nil {
			return fmt.Errorf("error reading 'id': %w", err)
		}
		delete(object, "id")
	}

	if raw, found := object["name"]; found {
		err = json.Unmarshal(raw, &a.Name)
		if err != nil {
			return fmt.Errorf("error reading 'name': %w", err)
		}
		delete(object, "name")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for RegisterResponseWeb to handle AdditionalProperties
func (a RegisterResponseWeb) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.AccessToken != nil {
		object["access_token"], err = json.Marshal(a.AccessToken)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'access_token': %w", err)
		}
	}

	if a.Email != nil {
		object["email"], err = json.Marshal(a.Email)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'email': %w", err)
		}
	}

	if a.Id != nil {
		object["id"], err = json.Marshal(a.Id)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'id': %w", err)
		}
	}

	if a.Name != nil {
		object["name"], err = json.Marshal(a.Name)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'name': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
